[package]
name = "carrier-custom-service-example"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]
edition = "2018"

[dependencies]
carrier     = "0.9"
env_logger  = "0.6.2"
prost       = "0.5.0"
bytes       = "*"
mio-extras  = "*"


[build-dependencies]
prost-build = "0.5.0"
